version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123@Malik
      MYSQL_DATABASE: roof_deals_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: ./app
    container_name: python_app
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  db_data:
